### ISSUE TITLE
Add a button to allow the bot to leave the voice channel

### ISSUE THREAD

**Issue by canccevik** [canccevik/nimble-discord-bot#2]
## Feature
Currently, we are using the "stop" command to make the bot leave the voice channel. However, it would be more user-friendly to have a dedicated button for this action.

## To Do
- [ ] Remove the "stop" command from the bot's functionality.
- [ ] Implement a new button with the label "Stop" to serve as a visual cue for users.
- [ ] Add an interaction handler specifically for the "stop" button.
- [ ] Implement the necessary functionality in the handler to force the bot to leave the voice channel when the button is clicked.

**Comment by furkangunduz** [comment]
I am working on it.
